// <auto-generated />
using System;
using EduApoyosBackend.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduApoyosBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722130708_AgregarHistorialEstados")]
    partial class AgregarHistorialEstados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosSolicitud", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Radicada",
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Validando",
                            Nombre = "En Revisión"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Aceptada",
                            Nombre = "Aprobada"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "No cumple requisitos",
                            Nombre = "Rechazada"
                        });
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.Estudiante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramaAcademicoId")
                        .HasColumnType("int");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaAcademicoId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Estudiantes", (string)null);
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialesEstados", (string)null);
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.ProgramaAcademico", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgramasAcademicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Ingeniería de Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Medicina"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Derecho"
                        });
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Asesor"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Estudiante"
                        });
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.SolicitudApoyo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoSolicitudId")
                        .HasColumnType("int");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<double>("MontoSolicitado")
                        .HasColumnType("float");

                    b.Property<int>("TipoApoyoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsesorId");

                    b.HasIndex("EstadoSolicitudId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("TipoApoyoId");

                    b.ToTable("SolicitudesApoyo", (string)null);
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.TipoApoyo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposApoyo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Apoyo financiero mensual",
                            Nombre = "Económico"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Acceso a comedores universitarios",
                            Nombre = "Alimentario"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Subsidio de transporte urbano",
                            Nombre = "Transporte"
                        });
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "CC",
                            Descripcion = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "TI",
                            Descripcion = "Tarjeta de Identidad"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PS",
                            Descripcion = "Pasaporte"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "CE",
                            Descripcion = "Cédula de Extranjería"
                        });
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("EduApoyosBackend.Domain.Entities.ProgramaAcademico", "ProgramaAcademico")
                        .WithMany()
                        .HasForeignKey("ProgramaAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduApoyosBackend.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduApoyosBackend.Domain.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("EduApoyosBackend.Domain.Entities.Estudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramaAcademico");

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("EduApoyosBackend.Domain.Entities.EstadoSolicitud", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EduApoyosBackend.Domain.Entities.EstadoSolicitud", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduApoyosBackend.Domain.Entities.SolicitudApoyo", "Solicitud")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduApoyosBackend.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.SolicitudApoyo", b =>
                {
                    b.HasOne("EduApoyosBackend.Domain.Entities.Usuario", "Asesor")
                        .WithMany()
                        .HasForeignKey("AsesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduApoyosBackend.Domain.Entities.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany()
                        .HasForeignKey("EstadoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduApoyosBackend.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Solicitudes")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduApoyosBackend.Domain.Entities.TipoApoyo", "TipoApoyo")
                        .WithMany()
                        .HasForeignKey("TipoApoyoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asesor");

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Estudiante");

                    b.Navigation("TipoApoyo");
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("EduApoyosBackend.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("EduApoyosBackend.Domain.Entities.SolicitudApoyo", b =>
                {
                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
